[project]
name = "strategy-backtest"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "yfinance>=1.2.0",
]

[project.scripts]
sb = "strategy_backtest.cli:main"

[dependency-groups]
dev = [
    "pytest>=9.0.2",
]
